
define level.width 10
define level.height 15

postpone {
    leveldata:
    .1:
        z = btype.NULL
        a = btype.RED
        b = btype.GREEN
        c = btype.BLUE
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
        db a,a,a,a,a,a,a,a,a,a
        db b,b,b,b,b,b,b,b,b,b
        db c,c,c,c,c,c,c,c,c,c
        db b,b,b,b,b,b,b,b,b,b
        db a,a,a,a,a,a,a,a,a,a
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
        db z,z,z,z,z,z,z,z,z,z
}
